### ISSUE TITLE
market orders on coinbase

### ISSUE THREAD

**Issue by nirno** [blankly-finance/blankly#209]
On Coinbase, you don't have to specify size for market order.  Instead, you can specify the total sum (fees included) for which you want to buy, and Coinbase calculates the appropriate size so that `size * (market price at the moment) + fees == (total sum)`.  (This is convenient because it precludes the possibility for the trade to fail because the price has increased so much that `size * price > (available money)`.)  I have not found a way to issue market orders in this way with Blankly.  Is it possible or, if not, will it be possible any time soon?

**Comment by EmersonDove** [comment]
This is a good question. In our case we keep strictly to the base size for both buy and sell orders mainly because it maintains really high compatibility with other APIs like Binance or Alpaca. We generally went with this design decision because as you mentioned in your comment is very easy to convert between funds and size.
