### ISSUE TITLE
Blankly Platform - self-hosting

### ISSUE THREAD

**Issue by uneknown** [blankly-finance/blankly#225]
There is no longer a hosted version of the Blankly Platform available. On the website, it states, "We're going completely open source!". For self-hosting purposes, where can I access the platform's source code?

**Comment by EmersonDove** [comment]
You're right, I'm still working on getting the open source distribution available, I'll finish that up and then let you know here!

**Comment by DigitalGreyHat** [comment]
Can you provide an ETA?

**Comment by EmersonDove** [comment]
I've finished up the platform which was the bulk of it, hoping to get it up sometime this week or during the weekend.

Some info on the scope, I'll be releasing:
- the platform codebase minus billing and the tradingview advanced charts because those are under a tradingview license
- the blankly kubernetes driving code (deploying, deleting, updating)
- the process management for hosted models (two code bases)
- quant metrics service
- website, both package & platform
- platform cloud functions
- model events service (for aggregating live model information)
- Some initial terraform // HCL code for provisioning the cloud
- Docker base images

I'll be skipping the data code (for the platform charts), usage metrics and a few other internal tools but I'll write some docs on how to integrate those.

Hopefully that gives you an idea of the scope and why it's taken awhile.

**Comment by EmersonDove** [comment]
Just an update I'll be pushing all the code in a few days to this [repo:

https://](https://github.com/blankly-finance/blankly-os)

I recommend using the github watch function so you'll know when it releases!

**Comment by reno-ha** [comment]
can't wait to see!

**Comment by EmersonDove** [comment]
Had some issues with git LFS getting it out but got it done.

Check it out here & give a star!

https://github.com/blankly-finance/blankly-os
