### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [blankly-finance/blankly#69]
I am not sure if some in the financial services industry would be comfortable with a *GPL license. I think something like AL 2.0, MIT, BSD would be better for wider usage and adaptation. Is there a particular reason a *GPL license has been used?

- Quantopian used AL 2.0
- QuantConnect is using AL 2.0

**Comment by EmersonDove** [comment]
Great question and I'm glad we're getting a chance to address it!

We chose LGPL because it strikes a clean balance between protecting our code and allowing people to use it in their closed-source code. **Just like the organizations you mention, we're hoping that we can move to Apache 2.0 as we grow & establish ourselves in the scene**. This is similar to how QC moved from closed source to Apache).

Our interpretation is that importing external python libraries into your code is permissible under LGPL. From [wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License):

_"Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided."_

Because we are writing valuable code that provides more than what other paid services provide, we have to start out by protecting the library before steadily loosening those restrictions.

**Comment by sirinath** [comment]
How would LGPL protect your code? 

What it will do is others have to publish their changes but when it comes to merging the code into your code base you would have to get the code licensed (through a contributor license agreement) otherwise you would loose the control over the code as now you would be forced to comply with LGPL and you cannot even relicense and change the license without everyone's permission . If you plan to provide tightly coupled infrastructure around the open source code this might become problematic also. 

Also people in the financial services industry would more concerned with using libraries which are not permissive. 

In my opinion your best bet is to go all out and increase the number of users, broker integrations, etc., regardless how they use it.

**Comment by EmersonDove** [comment]
You're right, we've had to balance all of this with the contributor agreements that come with the space.

With our increasing user base and the interest of contributing, this might be sign that we should migrate to Apache now before the agreements get more complicated.

**Comment by sirinath** [comment]
I see there are few merged PRs from 3rd patties. Are you keeping a Contributor License Agreement? Otherwise these merged code does not belong to you but licensed to you under LGPL. This would become very problematic for you and a company if you have to make changes on the hosted versions then time comes to move AL 2.0.

**Comment by EmersonDove** [comment]
Yep, all contributors have agreed to the CLA

**Comment by sirinath** [comment]
Any news on transitioning to Apache 2.0?

**Comment by EmersonDove** [comment]
I think we're going to stick with LGPL, I think it fits our goals and the industry the best.
