### ISSUE TITLE
Improve error messages if a symbol pair is not found.

### ISSUE THREAD

**Issue by rmonvfer** [blankly-finance/blankly#80]
While using Coinbase Pro I made a typo and used "XRP-USD" as the price_event symbol, blankly raised a generic error message (thrown at https://github.com/Blankly-Finance/Blankly/blob/main/blankly/exchanges/interfaces/coinbase_pro/coinbase_pro_interface.py#L463) which didn't really help.

I'm willing to help adding a more fine-grained exception control and helpful error messages wherever needed.

**Comment by EmersonDove** [comment]
This is a good idea. I largely haven't tackled exceptions because the different exchanges vary so widely and sometimes are difficult to parse.

If you wanted to get this started by adding a lookup table such as:

```python
generate_error_message(exchange: str, interface_call: str, exchange_error: str) -> str:
   if exchange == 'coinbase_pro':
       if interface_call == 'get_product_history':
           if exchange_error == 'NotFound':
                return 'Specified symbol not found.'
           else
                # or elif to other responses for this endpoint
                return exchange_error
       else:
           # or elif to other api calls
           return exchange_error
   else:
       # or elif to other exchanges
       return exchange_error
``` 

There are many implementations I could see but a simple lookup table for this would drive it at the core I believe.

We are still working on getting together our Contributor License Agreement so I may have to leave a pull request hanging until we can figure all that out.

**Comment by rmonvfer** [comment]
Sure! I'd love to give it a try, I'll work on it and submit a PR.
@ me if I can help with something else.
