### ISSUE TITLE
Feature request: Default to minimum possible resolution

### ISSUE THREAD

**Issue by sjhermanek** [Blankly-Finance/Blankly#85]
## Description
When trying to  inter-operate the same strategy with various currencies, it'd be great to get a helper (a la `trunc`) to default to minimum possible resolution. For instance, BTC-USD resolution may be higher than SOL-USD.

## Error
```
blankly.utils.exceptions.InvalidOrder: Size resolution is too high, the highest resolution allowed for this symbol is: 0.01. You specified 60.405. Try using blankly.trunc(size, decimal_number) to match the exchange resolution.
```

**Comment by EmersonDove** [comment]
I got you!

You should be able to use `interface.get_oder_filter()` to easily inform your trunc. 

Do you mean a `trunc` that automatically finds the resolution and uses that?

The real reason why we don't convert for you is because I have always unsure if it is our place to modify people's order amounts because they might be doing something I can't anticipate. I am open to ideas on this decision though.

**Comment by sjhermanek** [comment]
Amazing @EmersonDove, so glad to hear this! I think `get_order_filter()` will do the job for me.

Also agree that we shouldn't be overly prescriptive within `trunc` since, well, it keeps the method well-scoped and there may be use-cases for submitting super-small orders (e.g. I could imagine an exchange that would accept these orders but not fill them, so this could be a good way of probing for execut-ability).
